### ISSUE TITLE
Java JPMS modules

### ISSUE THREAD

**Issue by gregw** [eclipse-ee4j/servlet-api#201]
The servlet API artefact should be consumable as a JPMS module for java 11

**Comment by sbordet** [comment]
This is really important for Servlet Containers such as Jetty, Tomcat, Undertow, etc.

Artifacts from such projects won't be able to be converted to JPMS modules because they depend on the servlet API which is not a JPMS module itself.

Maven gives a warning if a JPMS module depend on a jar that is not a JPMS module:

```
[WARNING] * Required filename-based automodules detected. Please don't publish this project to a public artifact repository! *
```

**Comment by sbordet** [comment]
The Servlet API only depend on `java.base`.

Given that, there is a small difference between using a proper `module-info.java` and `Automatic-Module-Name` in the `MANIFEST`.

Using `module-info.java` would require a more complex Maven setup to create a multi-release jar (see [here](https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html)).
Multi-release jars may be troublesome to parse, see for example eclipse/jetty.project#1797.

I am proposing that the Servlet API just uses `Automatic-Module-Name`, with a name of `javax.servlet.api`.

Unfortunately it cannot be the same name as the OSGi bundle symbolic name, which is `javax.servlet-api` because the dash `-` is not allowed in JPMS module names.

I will prepare a pull request.

**Comment by sbordet** [comment]
@gregw @stuartwdouglas @markt-asf what is the process to get a release with this fix in Maven Central, so that Servlet Containers can start experimenting on modularizing?

**Comment by markt-asf** [comment]
It will be included in the first release from Eclipse. That is a process all of the EE4J projects are working through at the moment. As it is the first release there is quite a bit of stuff that needs to be put in place. Current planning is that the first release from the spec projects will be late October / early November. Personally, I'm expecting that to slip.
There is nothing stopping the implementations that ship their own servlet-api JARs including this fix. I plan to add this to Tomcat for the next set of releases which should be in early October.

**Comment by gregw** [comment]
The PMC [recommends using jakarta.*](https://github.com/eclipse-ee4j/ee4j/issues/34) as module names for the Jakarta EE specification projects.

**Comment by markt-asf** [comment]
Sorry, no idea. There is a release in progress but it started while I was on PTO and the requirements were such a moving target I was unable to follow what was going on. Since I got back I haven't found the time to get back up to speed on the current status and figure out the current status. I'm sure one of the other project committers will be able to provide a better idea of the current status of this issue than me.

**Comment by gregw** [comment]
A JPMS Automatic module name is included in the 4.0.3 release: https://github.com/eclipse-ee4j/servlet-api/blob/4.0.3-RELEASE/api/pom.xml#L193-L195

**Comment by Thihup** [comment]
Would now be possible to include a proper module-info for the next release?

**Comment by arjantijms** [comment]
+1 As Servlet committer it would definitely support this, though we may need to coordinate at the platform level to have consistent module names.
