### ISSUE TITLE
Update Scope Statement for Jakarta Servlet Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/servlet-api#239]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by chkal** [comment]
Draft:

> Jakarta Servlet provides a specification document, API and TCK for interacting with the web on the Jakarta EE platform.

Based on the wording in the original [project proposal](https://projects.eclipse.org/projects/ee4j.servlet/reviews/creation-review).

**Comment by chkal** [comment]
Any feedback on this proposal?

**Comment by arjantijms** [comment]
Perhaps this one needs a little tuning, although it's a good start.

Interacting with the web, in essence, is what JAX-RS, JAX-WS, WebSocket, JSF and MVC are also doing. 

We probably don't want the Servlet scope to be so broadly stated that it could effectively become JSF (this is of course very far fetched, but just for an extreme example).

Ideally the Servlet scope would explain in a concise wording that's it's a "thin" usability layer on top of HTTP. So its API is higher level than Grizzly or Netty, which are more bare HTTP and other protocol engines, but lower level than JAX-RS.

For better or worse, the Servlet spec also implies implementations having this HTTP engine on top of which its a usability layer, and it contains the core concepts of deploying war achives, and also has some of the security fundamentals. The latter have been formalised in among others the JACC spec, but have not been moved to there, so have always remained in Servlet as well.

So given all of the above, "interacting with the web" might not fully explain what Servlet does.

**Comment by stuartwdouglas** [comment]
I prefer the one in the example spreadsheet:

>Jakarta Servlet provides a specification document, API, and TCK that defines a Java-based means of implementing the HTTP request/response paradigm over network services.

With some minor tweaks:

>Jakarta Servlet provides a specification document, API, and TCK that defines a means of implementing the HTTP request/response paradigm

I don't think we need to include everything that is in Servlet as part of the statement, but I also don't really like 'interacting with the web' as this could also be taken to include websockets, SSE etc.

**Comment by waynebeaton** [comment]
If we boil this down to just what the specification itself defines, we're left with this:

> Jakarta Servlet defines a means of implementing the HTTP request/response paradigm.

That actually feels like enough to me.

I might want to add "for Jakarta EE applications", but I'm not sure that it adds any value.

**Comment by bshannon** [comment]
Another key aspect is that it defines a packaging model for such applications.

> Jakarta Servlet defines a server-side API for handling HTTP requests and responses,
> and a packaging model for such server-side applications.

**Comment by stuartwdouglas** [comment]
I would rather leave the bit about packaging off. There are lots of
frameworks that use Servlet that are not using a traditional application
server packaging model.

**Comment by bshannon** [comment]
Yet it is part of the spec and thus in scope.

**Comment by waynebeaton** [comment]
I agree with @bshannon. The scope of the specification includes packaging. That some frameworks only implement part of the spec is irrelevant.

Note that in order to claim compatibility with a specification, all non-optional parts of the specification must be implemented.

**Comment by stuartwdouglas** [comment]
That is currently the case, but given that a lot of modern runtimes are moving away from the war packaging it seems like this area of the spec would be a good candidate for evolution, either by making the war packaging optional in the standalone case, or by also defining a standard layout for jar based web deployments.

This obviously would need to be discussed in depth on the list first, but I think we should leave the scope as broad as possible in this case.

**Comment by gregw** [comment]
I think we can leave out the part about defining "a packaging model", because that is describing how the spec is implemented to "defines a server-side API for handling HTTP requests and responses".  It also defines class interfaces, but we don't call that out specifically.   Sure packaging is and will be part of the specification for how to handle server side HTTP, but I don't think we need to go for a fat description.   In the same way, we could probably drop "API" (specially as we have some concrete classes) and we get:

> Jakarta Servlet defines server-side handling for HTTP requests and responses

**Comment by arjantijms** [comment]
I agree with @gregw that we can't put everything into the scope, but the packaging model is quite fundamental and something that is specifically defined in Servlet. 

One would intuitively think this packaging model is defined at the Jakarta EE platform level, and probably that is where it's ultimately better to put this, but for now and probably some time to come it's in Servlet.

**Comment by bshannon** [comment]
The packaging model is not an implementation detail, it's actually a required part of the spec.
If it's not in the scope, the spec can't include it, and the Jakarta EE 8 spec would no longer
match the Java EE 8 spec.

If you want the packaging model out of the spec, that would be a discussion for a future version
of the spec.  Just because the scope includes packaging doesn't mean that the spec always
has to include packaging.

**Comment by waynebeaton** [comment]
Can somebody please drive this to conclusion?

**Comment by stuartwdouglas** [comment]
I am happy with Greg's proposed definition: 'Jakarta Servlet defines server-side handling for HTTP requests and responses'

I don't think the argument 'if it is not in the scope we cannot include it' is correct, otherwise we also need to mention security, XML descriptors etc and it will be way too long.

**Comment by bshannon** [comment]
As I understand the Eclipse policy, if it is not in scope you can't include it.
That's how we make sure projects are doing what they say they're going
to do and there are no IP surprises.  Obviously you have to allow some room
for interpretation.  Handling security of requests and response might reasonably
be considered in scope, but the packaging model seems completely different
and in no way is implied by "handling requests and responses".

I'll leave it to @waynebeaton who better understands how these scope statements
should be constructed, but I still think at least packaging (which is the part that
defines the deployment descriptors) should be included, and I wouldn't object to
mentioning security as well.

**Comment by waynebeaton** [comment]
Developing a good scope statement is a bit of an art form. We don't want it to be so specific that the project team can't innovate at all; nor do we want it to be so vague that everything under the sun is in play.

A primary purpose of the scope statement is to provide some boundaries around the project so that Eclipse Foundation Members (especially those involved with specifications) can understand the potential intellectual property footprint of the project/specification.

> Jakarta Servlet defines server-side handling for HTTP requests and responses

So, does this reasonably imply packaging and security? I think it does (yes, I realize that I've changed my mind; again, this is more art than science). XML descriptors really feels like an implementation detail that, while important, is unnecessarily restrictive and not a fundamental aspect of this specification (a future YAML-based descriptor horror show should not, I believe, have any impact on the nature of the specification or its intellectual property footprint).

I think that we can also reasonably argue that this scope excludes higher-level concepts like web services, or Jakarta Server Pages/Faces.

So, this is enough for me. The real test, however, is the Specification Committee vote to approve it.

**Comment by bshannon** [comment]
I guess we should see what the Spec Committee says.  They may just say
"it's Servlets, we know what it is".  But I still claim that nothing in that scope
statement implies or suggests that an application packaging model will be
included.

This isn't really an issue for Servlets because we're going to approve it no
matter what the scope statement says.  It's more a test of how scope statements
effect what can be developed in a project, which will  have IP implications for
future specs.

**Comment by waynebeaton** [comment]
Consensus appears to be that the scope should be:

> Jakarta Servlet defines server-side handling for HTTP requests and responses.

I'll take this to the Specification Committee for approval.

**Comment by gregw** [comment]
Sorry late to comment as I've been travelling.

I do agree that a scope should be as descriptive as possible, but in this case I think that the risk is that "defines server-side handling for HTTP requests and responses" might suffer scope creep towards higher-level concepts like web services, or Jakarta Server Pages/Faces... as it has done in the past by treating JSP specially.

I'm not sure that there is significant risk that we will define packaging model(s) in an abusive way.  Perhaps we may go from singular to plural packaging models and so the proposed singular "a packaging model" could have been restrictive.

So I'm happy with the language regarding packaging and I can't think of a good way to concisely restrict the scope to avoid feature creep into higher-level concepts.... so I'm good that wayne accepted the language as proposed.
