### ISSUE TITLE
Change project name to Jakarta Servlet

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/servlet-api#240]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [x]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by gregw** [comment]
I note that currently the project is referred to variously as "Java Servlet"  and "Java Servlet API".
So I think it worthwhile to also check/update the usage if "API".

I believe the technology in general is called "Jakarta Servlet", but this project should be specifically called "Jakarta Servlet API".... hence I will edit the title.

I note also that there is some discussion about renaming the top level git project from "eclipse-ee4j" to just "jakarta".    If that was done, then perhaps the github name can be "jakarta/servlet-api" rather than "jakarta/jakarta-servlet-api" - I've no strong preference either way... we should follow the herd.   So while we can start preparing a PR, let's not rush to merge anything too soon, just in case there are some variations that come from other projects.

**Comment by ivargrimstad** [comment]
Suggest to remove API from the name for consistency with the other projects, thus rename to Jakarta Servlet.

**Comment by arjantijms** [comment]
>Suggest to remove API from the name for consistency with the other projects, thus rename to Jakarta Servlet.

+1

**Comment by gregw** [comment]
Do we need to change the automatic module name (here)[https://github.com/eclipse-ee4j/servlet-api/blob/master/api/pom.xml#L194] to `jakarta.servlet` ?

**Comment by gregw** [comment]
@stuartwdouglas @arjantijms @bshannon I think we have more renaming to do.  At the very least we need to fix the [OSGi manifest](https://github.com/eclipse-ee4j/servlet-api/blob/master/api/pom.xml#L163) and perhaps the JPMS module name as well.   So if it is not too late, can we fix and reroll release?
