### ISSUE TITLE
Relative ordering of web fragments

### ISSUE THREAD

**Issue by Thihup** [eclipse-ee4j/servlet-api#365]
The spec says that valid ordering of the may be one of:
```
B, E, F, <no id>, C, D
B, E, F, <no id>, D, C
E, B, F, <no id>, C, D
E, B, F, <no id>, D, C
E, B, F, D, <no id>, C
E, B, F, D, <no id>, D
```
However, the last one repeats the "D" fragment,
Is this really valid or this should be `E, B, F, C, <no id>, D`?

**Comment by markt-asf** [comment]
I don't think that is quite right as `<no id>` has to be before `C`.  I think it should be:
```
B, E, F, <no id>, C, D
B, E, F, <no id>, D, C
E, B, F, <no id>, C, D
E, B, F, <no id>, D, C
E, B, F, D, <no id>, C
B, E, F, D, <no id>, C
```
I'd be tempted to reorder the list as well but for clarity I think I'll just correct the last line.
I'll provide a PR.

**Comment by gregw** [comment]
@janbartel ?

**Comment by janbartel** [comment]
@gregw  I think @markt-asf is right and the last line is wrong: the last element _must_ be `C` because `<no id>` must always be before `C`, and `B E F` can be in the order he shows.

It seems a little odd that that `D` could be interposed between `<no id>` and `C` but technically  that maintains the relationship of `<no id>` before `C` so the spec is satisfied.
